[package]
name = "tokio-socketcan"
version = "0.2.0"
authors = ["Terry Kerr <root@oefd.ca>"]
edition = "2018"
description = "Asynchronous Linux SocketCAN sockets with tokio"
license = "MIT"
repository = "https://github.com/oefd/tokio-socketcan"

[dependencies]
socketcan = "1.7"
futures = "0.3"
mio = "0.7"
libc = "0.2"
thiserror = "1.0"
tokio = { version = "1.1", features = ["net"] }

[dev-dependencies]
futures-timer = "3.0"
futures-util = "0.3"

[dev-dependencies.tokio]
version = "*"
# required for tokio::test
features = ["macros", "rt-multi-thread"]
